# https://docs.lando.dev/

name: php-cs-fixer

services:
  php:
    type: php
    via: cli
    build_as_root:
      - docker-php-ext-enable xdebug
    overrides:
      environment:
        XDEBUG_MODE: coverage

tooling:
  php:
    service: php
    cmd: php

  composer:
    service: php
    cmd: composer
